apiVersion: v1
kind: Secret
metadata:
  name: todolist-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: todolist
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SESSION_KEY:    {{ .Values.app.secret.SESSION_KEY | quote }}
  ADMIN_USER:     {{ .Values.app.secret.ADMIN_USER | quote }}
  ADMIN_PASSWORD: {{ .Values.app.secret.ADMIN_PASSWORD | quote }}
  CLEANUP_TOKEN:  {{ .Values.app.secret.CLEANUP_TOKEN | quote }}
