apiVersion: v1
kind: ServiceAccount
metadata:
  name: todolist
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: todolist
    app.kubernetes.io/instance: {{ .Release.Name }}
