apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: todolist
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: todolist
  ports:
    - name: http
      port: 80
      targetPort: http
